In [1]:
import numpy as np
#numpy.__version__
#np.__version__

In [4]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\BrandonManuelPercast\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\brandonmanuelpercast\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> imp

In [5]:
#Arreglo de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([3.14, 4, 2, 3], dtype = np.float32)

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [9]:
#Anidar listas resulta en arreglos multidimencionales
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
#Crear un arreglo de enteros de longitud 10  lleno con 0s
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#Crear un a arreglo de 3x5 de punto flotante lleno con 1's
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#Crear un arreglo de 3x5 lleno con 3.14

np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
#Crear un aareglo lleno con una secuencia lineal
#iniciando en 0, y terminando en 20, con paso de 2
#(Es similar a contruir una función "range")

#inicio, final, paso
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
#Crear un arreglo de conco valores uniformemente espaciados entre 0 y 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
#Crear un arreglo de 3x3 uniformemente distribuido
#Valores seudoaleatorios entre 0 y 1

np.random.random((3, 3))

array([[0.99395706, 0.07270205, 0.54731611],
       [0.6610502 , 0.29549024, 0.13443807],
       [0.09273066, 0.37666236, 0.98861332]])

In [26]:
#Crear un arreglo 3x3 normalmente distribuido seudo aleatorio
#Valores con media 0 y desviación estandar 1

np.random.normal(0, 1, (3, 3))

array([[-1.00200179, -0.98845207,  1.34687969],
       [ 1.12218374, -0.48814558, -0.00328174],
       [-0.23850279,  1.38633242,  0.63864008]])

In [28]:
#Crear un arreglo 3x3 de seudoenteros en un intervalo de [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 5, 4],
       [6, 2, 6],
       [1, 8, 5]], dtype=int32)

In [30]:
#Crear un matriz identidad 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Crear un arreglo unidimensional de tres enteros; los valores deben 

np.empty(3)

array([1., 1., 1.])

In [3]:
rng = np.random.default_rng(seed = 1701)

In [4]:
x1 = rng.integers(10, size = 6) #arreglo unidimensional
x2 = rng.integers(10, size = (3, 4)) #arreglo bidimensional
x3 = rng.integers(10, size = (3, 4, 5)) #arreglo tridimensional

In [6]:
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)
print("x3 dtype", x3.dtype)
print("x3 itemsize", x3.itemsize)
print("x3 nbytes", x3.nbytes)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60
x3 dtype int64
x3 itemsize 8
x3 nbytes 480


In [7]:
x3

array([[[9, 2, 7, 2, 5],
        [3, 6, 8, 2, 0],
        [6, 5, 8, 4, 3],
        [2, 4, 3, 9, 2]],

       [[3, 6, 1, 3, 0],
        [0, 1, 9, 5, 4],
        [7, 8, 1, 7, 3],
        [9, 7, 6, 4, 8]],

       [[0, 9, 2, 7, 2],
        [4, 8, 7, 0, 7],
        [8, 3, 0, 4, 9],
        [3, 2, 5, 5, 4]]])

In [8]:
x1

array([9, 3, 6, 6, 5, 0])

In [9]:
x1[0]

np.int64(9)

In [10]:
x1[4]

np.int64(5)

In [11]:
x1[-1]

np.int64(0)

In [12]:
x1[-2]

np.int64(5)

In [13]:
x2

array([[2, 5, 6, 4],
       [8, 2, 5, 6],
       [2, 7, 3, 8]])

In [14]:
x2[0, 0]

np.int64(2)

In [15]:
x2[2, 0]

np.int64(2)

In [16]:
x2[2,-1]

np.int64(8)

In [17]:
x2
x2[0, 0] = 12
x2

array([[12,  5,  6,  4],
       [ 8,  2,  5,  6],
       [ 2,  7,  3,  8]])

In [20]:
x1

array([8, 3, 7, 2, 3, 2])

In [ ]:
#Primeros 3 elementos
x1[:3]

array([8, 3, 7])

In [21]:
#elementos despues del 3
x1[3:]

array([2, 3, 2])

In [22]:
#Mitad del subarreglo
x1[1:4]

array([3, 7, 2])

In [23]:
#cada dos elementos
x1[::2]

array([8, 7, 3])

In [25]:
#Todos los elementos a la inversa
x1[::-1]

array([2, 3, 2, 7, 3, 8])

In [ ]:
#Cada dos elementos a la inversa desde el indice 4
x1[4::-2]

array([3, 7, 8])

In [6]:
#Arreglo multidimensional
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [5]:
#Primeras 2 filas y 3 columnas
x2[:2 , :3]

array([[3, 1, 3],
       [4, 0, 2]])

In [10]:
#Tres filas y cada segunda columna
x2[:3, ::2]

array([[3, 3],
       [4, 2],
       [0, 6]])

In [11]:
#Todas las filas y columnas a la inversa
x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [12]:
#Primer columna de x2
x2[:,0]

array([3, 4, 0])

In [13]:
#Primer fila de x2
x2[0, :]

array([3, 1, 3, 7])

In [14]:
#Equivalencia de x2[0, :]
x2[0]

array([3, 1, 3, 7])

In [16]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [15]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 1]
 [4 0]]


In [17]:
x2_sub [0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [18]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [19]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [20]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [21]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


### Remodelación de matrices

In [26]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
grid.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) #Vector fila via reshape

array([[1, 2, 3]])

In [29]:
x.reshape((3, 1)) #Vector columna via reshape

array([[1],
       [2],
       [3]])

In [30]:
#Vector fila con newaxis
x[np.newaxis, :] 

array([[1, 2, 3]])

In [31]:
#Vector columna con newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Concatenar y dividir arreglos

In [32]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [33]:
z = np.array([99, 99, 99])

print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [48]:
grind = np.array([[1, 2, 3],
                 [4, 5, 6]])

grind

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#concatenar a traves del primer eje

#np.concatenate([grid, grid]) #No funciono, pero deveria ser:

np.concatenate([grind, grind], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
#Concatenar a traves del eje secundarios (idexado - cero)

np.concatenate([grind, grind], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
#Apilamiento vertical de arreglos
np.vstack([x, grind])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
#Apilamiento horizontal de arreglos
y = np.array([[99],
             [99]])

np.hstack([grind, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [50]:
grind

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #Los indices 3 y 5 indican en donde se realizarán los corte son exclusivos para cada corte
#para x1 se consideran los indeces del 0 al 3 (exclusivo)
#para x2 se consideran los indices del 3 (inclusivo) al 5 (exclusivo)
#para x2 se consideran los indices del 5 (inclusivo) hasta el final
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [58]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Capítulo 6
## Calculos sobre arreglos de numpy: Funciones universales

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1, 10, size=5)
compute_reciprocal(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [3]:
values

array([9, 4, 1, 3, 8])

In [5]:
big_array = rng.integers(1, 10, size = 1000000)
%timeit compute_reciprocal(big_array)

2.19 s ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit (1.0 / big_array)

5.37 ms ± 386 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
#Ya se opero entre escalares y un arreglo, pero también se puede operar entre dos arreglos

np.arange(5) / np.arange(1, 6)

# También se puede operar entre dos arreglos de la misma longitud:
np.arange(5) ** np.arange(5)

# Y se pueden operar entre un escalar y un arreglo:
np.arange(5) ** 2

# También se

array([ 0,  1,  4,  9, 16])

In [8]:
#Las funciones universales o UFUNC, no se limitan a arregle unidimensionales
x = np.arange(9).reshape((3, 3))

2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Explorando Ufuncs de Numpy
#### Aritmetica de arreglos

In [11]:
x = np.arange(4)

print("x = ", x)
print("x + 5 = ", x +5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x // 2 = ", x // 2) #división piso

x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [ ]:
#Función unitaria para la negación, exponenciación y modulo

print("-x = ",-x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


### Valor absoluto

In [13]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [14]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [15]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [16]:
#También funciona con números completos
#Aquí se denotan con la letra "j"

x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Funciones trigronometricas

In [17]:
theta = np.linspace(0, np.pi, 3)

In [18]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [19]:
#Las funciones trigonometricas inversas también están disponibles

x = [-1, 0, 1]
print("x =", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x = [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponenciales y Logaritmos

In [2]:
import numpy as np

x = [1, 2, 3]

print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3., x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3.  9. 27.]


In [3]:
x = [1, 2, 3, 10]

print("x = ", x)
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 3, 10]
ln(x) =  [0.         0.69314718 1.09861229 2.30258509]
log2(x) =  [0.         1.         1.5849625  3.32192809]
log10(x) =  [0.         0.30103    0.47712125 1.        ]


In [4]:
#Versión especializada para mantener la presición con entradas muy pequeñas
x = [0, 0.001, 0.01, 0.1]

print("exp(x) -1 = ", np.expm1(x))
print("log(1 + x) = ", np.log1p(x))

exp(x) -1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) =  [0.         0.0009995  0.00995033 0.09531018]


### Matematicas obscuras

In [5]:
from scipy import special

#Función Gamma (Factoriales Generalizados) y funcionesrelacionadas

x = [1, 5, 10]

print("gamma(x) = ", special.gamma(x))
print("ln|gamma(x)| = ", special.gammaln(x))
print("beta(x, 2) = ", special.beta(x, 2))

gamma(x) =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| =  [ 0.          3.17805383 12.80182748]
beta(x, 2) =  [0.5        0.03333333 0.00909091]


In [6]:
#Función de Error (Integral de Gauss)

x = np.array([0, 0.3, 0.7, 1.0])

print("erf(x) = ", special.erf(x))
print("erfc(x) = ", special.erfc(x))
print("erfinv(x) = ", special.erfinv(x))

erf(x) =  [0.         0.32862676 0.67780119 0.84270079]
erfc(x) =  [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) =  [0.         0.27246271 0.73286908        inf]


In [7]:
#Para grandes calculos es algunas ocaciones útil especificar el arreglo donde el resultado del cálculo será almacenado

x = np.arange(5)
y = np.empty(5)

np.multiply(x, 10, out=y)

print(y)

[ 0. 10. 20. 30. 40.]


In [8]:
y = np.zeros(10)

np.power(2, x, out = y[::2])

print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
